# Generated by Django 5.0.3 on 2024-03-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn_messages',
            name='session_id',
        ),
        migrations.DeleteModel(
            name='Learn_Sessions',
        ),
    ]
