# Generated by Django 5.0.3 on 2024-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_learn_sessions_learn_messages_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn_messages',
            name='user_feedback',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
