# Generated by Django 5.0.3 on 2024-03-15 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_alter_learn_messages_user_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Learn_Messages',
            new_name='Learn_Message',
        ),
        migrations.RenameModel(
            old_name='Learn_Sessions',
            new_name='Learn_Session',
        ),
    ]
