# Generated by Django 5.0.3 on 2024-03-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_rename_learn_messages_learn_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learn_message',
            options={'verbose_name_plural': 'Learn Messages'},
        ),
        migrations.AlterModelOptions(
            name='learn_session',
            options={'verbose_name_plural': 'Learn Sessions'},
        ),
    ]
