# Generated by Django 5.0.3 on 2024-05-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_alter_learn_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn_message',
            name='user_feedback',
        ),
        migrations.AddField(
            model_name='learn_message',
            name='approved',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='learn_message',
            name='edited_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learn_message',
            name='feedback',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='learn_message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learn_message',
            name='response',
            field=models.TextField(),
        ),
    ]
