# Generated by Django 5.0.3 on 2024-05-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_remove_learn_message_user_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn_message',
            name='edited_message',
            field=models.TextField(blank=True),
        ),
    ]
