# Generated by Django 5.0.3 on 2024-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_remove_learn_message_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn_message',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='learn_message',
            name='user_feedback',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
